import React from 'react';
import { ArrowLeft, FileText, Scale, CheckCircle2 } from 'lucide-react';

interface TermsPageProps {
  onBackToHome: () => void;
}

export const TermsPage: React.FC<TermsPageProps> = ({ onBackToHome }) => {
  return (
    <div className="w-full max-w-4xl mx-auto px-4 sm:px-6 py-10 animate-in fade-in duration-300">
      {/* Top Back Navigation */}
      <div className="mb-8">
        <button
          id="terms-back-btn"
          onClick={onBackToHome}
          className="px-3.5 py-1.5 rounded-full border border-zinc-200 hover:bg-zinc-50 text-zinc-700 hover:text-zinc-950 transition-colors flex items-center gap-1.5 text-xs font-medium"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to Home</span>
        </button>
      </div>

      <div className="bg-white rounded-[24px] border border-zinc-200 p-8 sm:p-12 shadow-sm space-y-8">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-100 text-zinc-700 text-xs font-semibold tracking-wide mb-4">
            <Scale className="w-3.5 h-3.5 text-zinc-600" />
            <span>Legal Agreement</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold text-zinc-900 tracking-tight">
            Terms of Use
          </h1>
          <p className="text-xs text-zinc-400 font-mono mt-2">
            Effective Date: March 2026 • ProductReviews.Review Platform
          </p>
        </div>

        <div className="space-y-6 text-zinc-600 text-sm leading-relaxed font-normal">
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">1. Acceptance of Terms</h2>
            <p>
              By accessing or using <strong>productreviews.review</strong>, you agree to be bound by these Terms of Use and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">2. Permitted Use &amp; Intellectual Property</h2>
            <p>
              The content, algorithms, interface layouts, and comparative syntheses presented on productreviews.review are protected by applicable intellectual property and copyright laws. You are granted a limited, revocable license to access the site for personal, non-commercial product evaluation.
            </p>
            <p>
              You agree not to scrape, reverse-engineer, mass-republish, or systematically extract data from our multi-source review feeds without explicit prior written authorization.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">3. Nature of AI Content &amp; Analysis</h2>
            <p>
              The syntheses, pros/cons assessments, and RECOMMENDED / NOT RECOMMENDED classifications are generated by algorithmic synthesis of third-party public reviews, benchmarks, and community discussions. While we strive for rigorous accuracy, manufacturer specifications, firmware revisions, regional SKUs, and pricing are subject to rapid change. Users must verify critical parameters with official retailers before committing to purchases.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">4. Third-Party Websites &amp; Affiliate Links</h2>
            <p>
              Our service provides hyperlinks to external e-commerce merchants and retailers. We have no control over the content, terms, return policies, or practices of third-party websites. Accessing external links is conducted entirely at your own risk.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">5. Limitation of Liability</h2>
            <p>
              In no event shall productreviews.review or its operators be liable for any direct, indirect, incidental, consequential, or punitive damages arising out of your access to, use of, or inability to use the service or any products purchased via third-party retailer links.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-bold text-zinc-900">6. Modifications to Terms</h2>
            <p>
              We reserve the right to revise these Terms of Use at any time without advance notice. By continuing to use the service, you agree to be bound by the then-current version of these Terms.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
};
