/**
 * High-Priority Successful Product Comparison Registry
 * 
 * Defines high-intent decision engine comparison pages featured in ProductReviews.review.
 * Each entry maps two distinct products into a clean canonical slug (/compare/product-a-vs-product-b),
 * enabling Google Search Console to index decision pages directly.
 */

export interface ComparisonProductEntry {
  slug: string;
  productA: string;
  productB: string;
  category: 'Smartphones' | 'Laptops & PCs' | 'Cameras' | 'Audio & Headphones' | 'TVs & Displays' | 'Tablets' | 'Gaming' | 'Appliances & Home' | 'Wearables';
  priority: string; // e.g. '0.90' or '0.85'
  changefreq: 'daily' | 'weekly' | 'monthly';
  lastmod?: string;
  isSuccessful: boolean;
  verdictSummary?: string;
}

export const HIGH_PRIORITY_COMPARISONS: ComparisonProductEntry[] = [
  {
    slug: 'iphone-16-pro-vs-samsung-galaxy-s24-ultra',
    productA: 'Apple iPhone 16 Pro',
    productB: 'Samsung Galaxy S24 Ultra',
    category: 'Smartphones',
    priority: '0.95',
    changefreq: 'daily',
    isSuccessful: true,
    verdictSummary: 'Side-by-side assessment of A18 Pro vs Snapdragon 8 Gen 3, titanium durability, telephoto zoom, and long-term battery endurance.',
  },
  {
    slug: 'macbook-air-m3-vs-dell-xps-13',
    productA: 'Apple MacBook Air M3',
    productB: 'Dell XPS 13 (Snapdragon X Elite)',
    category: 'Laptops & PCs',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Comparison of ARM architecture efficiency, Liquid Retina vs OLED display quality, keyboard ergonomics, and battery endurance under daily workload.',
  },
  {
    slug: 'sony-a7-iv-vs-canon-eos-r6-mark-ii',
    productA: 'Sony A7 IV',
    productB: 'Canon EOS R6 Mark II',
    category: 'Cameras',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Head-to-head full-frame mirrorless evaluation covering autofocus tracking, 4K 60p thermal limits, dynamic range, and lens ecosystem availability.',
  },
  {
    slug: 'sony-wh-1000xm5-vs-bose-quietcomfort-ultra',
    productA: 'Sony WH-1000XM5',
    productB: 'Bose QuietComfort Ultra',
    category: 'Audio & Headphones',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Decibel attenuation shootout across commuter noise frequencies, voice isolation mic clarity, LDAC vs AptX Adaptive, and long-wear clamping pressure.',
  },
  {
    slug: 'ipad-pro-m4-vs-samsung-galaxy-tab-s9-ultra',
    productA: 'Apple iPad Pro M4',
    productB: 'Samsung Galaxy Tab S9 Ultra',
    category: 'Tablets',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Tandem OLED display evaluation, M4 performance vs Snapdragon 8 Gen 2, stylus latency, and desktop multitasking productivity.',
  },
  {
    slug: 'airpods-pro-2-vs-sony-wf-1000xm5',
    productA: 'Apple AirPods Pro 2 (USB-C)',
    productB: 'Sony WF-1000XM5',
    category: 'Audio & Headphones',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'In-ear ANC noise cancellation depth, transparency fidelity, spatial audio head tracking, and battery case longevity.',
  },
  {
    slug: 'lg-c3-oled-vs-samsung-s90c-oled',
    productA: 'LG C3 OLED TV',
    productB: 'Samsung S90C QD-OLED TV',
    category: 'TVs & Displays',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'WOLED vs QD-OLED peak luminance, Dolby Vision vs HDR10+ support, HDMI 2.1 gaming latency, and webOS vs Tizen smart features.',
  },
  {
    slug: 'playstation-5-pro-vs-xbox-series-x',
    productA: 'Sony PlayStation 5 Pro',
    productB: 'Microsoft Xbox Series X',
    category: 'Gaming',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'PSSR AI upscaling analysis, 60fps ray-tracing performance, DualSense haptics, and Game Pass vs PS Plus subscription value.',
  },
  {
    slug: 'asus-rog-ally-x-vs-steam-deck-oled',
    productA: 'ASUS ROG Ally X',
    productB: 'Valve Steam Deck OLED',
    category: 'Gaming',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: '80Wh battery endurance shootout, Ryzen Z1 Extreme Windows 11 compatibility vs SteamOS 90Hz HDR OLED fluid simplicity.',
  },
  {
    slug: 'dyson-v15-detect-vs-shark-stratos-cordless',
    productA: 'Dyson V15 Detect Cordless',
    productB: 'Shark Stratos Cordless Vacuum',
    category: 'Appliances & Home',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Laser dust detection accuracy, suction air-watts measurement, anti-hair-wrap roller performance, and multi-surface hardwood cleaning.',
  },
  {
    slug: 'google-pixel-9-pro-vs-iphone-16-pro',
    productA: 'Google Pixel 9 Pro',
    productB: 'Apple iPhone 16 Pro',
    category: 'Smartphones',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Tensor G4 AI photography suite vs A18 Pro computational video, Super Actua display brightness, and 7-year software updates.',
  },
  {
    slug: 'macbook-pro-m3-pro-vs-asus-rog-zephyrus-g14',
    productA: 'Apple MacBook Pro 14 (M3 Pro)',
    productB: 'ASUS ROG Zephyrus G14 (RTX 4070)',
    category: 'Laptops & PCs',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Creator workstation shootout testing 8K video rendering speeds, thermal fan noise, 3K OLED vs Liquid Retina XDR, and battery life off-charger.',
  },
  {
    slug: 'kindle-paperwhite-vs-kobo-clara-colour',
    productA: 'Amazon Kindle Paperwhite (11th Gen)',
    productB: 'Kobo Clara Colour',
    category: 'Tablets',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Color Kaleido 3 e-ink vs 300 PPI black-and-white E-Ink Carta 1200, warm light adjustment, waterproofing, and side-loading file format flexibility.',
  },
  {
    slug: 'apple-watch-ultra-2-vs-garmin-epix-pro',
    productA: 'Apple Watch Ultra 2',
    productB: 'Garmin Epix Pro Gen 2',
    category: 'Wearables',
    priority: '0.90',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Dual-frequency GPS tracking precision, 30-day battery endurance vs smartwatch app ecosystem, titanium case ruggedness, and AMOLED readability.',
  },
  {
    slug: 'sonos-era-300-vs-apple-homepod-2',
    productA: 'Sonos Era 300',
    productB: 'Apple HomePod (2nd Gen)',
    category: 'Audio & Headphones',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: 'Spatial Audio Dolby Atmos speaker array room-filling immersion, Trueplay tuning precision, Bluetooth line-in vs AirPlay 2 lock-in.',
  },
  {
    slug: 'oneplus-12-vs-samsung-galaxy-s24-plus',
    productA: 'OnePlus 12',
    productB: 'Samsung Galaxy S24+',
    category: 'Smartphones',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: '100W SUPERVOOC charging vs 45W Samsung fast charging, Hasselblad camera color science, LTPO AMOLED display, and price-to-performance value.',
  },
  {
    slug: 'ninja-creami-vs-vitamix-5200',
    productA: 'Ninja Creami Deluxe',
    productB: 'Vitamix 5200 Blender',
    category: 'Appliances & Home',
    priority: '0.80',
    changefreq: 'monthly',
    isSuccessful: true,
    verdictSummary: 'Micro-shaving freezing technology vs commercial-grade motor blade friction, protein ice cream texture, and cleanup convenience.',
  },
  {
    slug: 'roborock-s8-maxv-ultra-vs-dreame-l20-ultra',
    productA: 'Roborock S8 MaxV Ultra',
    productB: 'Dreame L20 Ultra Robot Vacuum',
    category: 'Appliances & Home',
    priority: '0.85',
    changefreq: 'weekly',
    isSuccessful: true,
    verdictSummary: '10,000Pa suction power shootout, automated mop washing & hot air drying dock, AI obstacle avoidance, and edge cleaning arm extension.',
  },
  {
    slug: 'anker-solix-c1000-vs-jackery-explorer-1000-v2',
    productA: 'Anker SOLIX C1000 Portable Power Station',
    productB: 'Jackery Explorer 1000 v2',
    category: 'Appliances & Home',
    priority: '0.80',
    changefreq: 'monthly',
    isSuccessful: true,
    verdictSummary: 'LiFePO4 battery lifespan (3,000+ cycles), 1800W continuous AC output, solar recharge input speed, and emergency blackout surge protection.',
  },
  {
    slug: 'bose-ultra-open-earbuds-vs-shokz-openrun-pro',
    productA: 'Bose Ultra Open Earbuds',
    productB: 'Shokz OpenRun Pro Bone Conduction',
    category: 'Audio & Headphones',
    priority: '0.80',
    changefreq: 'monthly',
    isSuccessful: true,
    verdictSummary: 'Open-ear spatial audio cuff design vs bone-conduction transducer bass resonance, ambient situational awareness, and runner sweat resistance.',
  },
];

export default HIGH_PRIORITY_COMPARISONS;
